import path from "path";
import fs from "fs/promises";
import "ts-replace-all";

import { StandardFolder, StandardOutputFolderTypeScript, TestFramework } from "rockmelonqa.common/file-defs";
import { IRunTestContext } from "rockmelonqa.common/ipc-defs";
import * as fileSystem from "../../utils/fileSystem";
import { StringBuilder } from "../../utils/stringBuilder";
import { EOL } from "os";
import { IAfterRunHandler } from "./afterRunHandler";

/** AfterRunHandler for Playwright Typescript project */
export default class AfterRunHandlerTypeScript implements IAfterRunHandler {
  /** Performs the handle  */
  async handle(context: IRunTestContext, logBuilder: StringBuilder) {
    const failedTestScreenshots = await this.getFailedTestScreenshots(context);
    if (failedTestScreenshots.length) {
      logBuilder.appendLine("");
      logBuilder.appendLine("*** Failed test screenshot files ***");
      logBuilder.appendLine(failedTestScreenshots.map((f) => `- ${f}`).join(EOL));
      logBuilder.appendLine("");

      await this.moveErrorScreenshotsToTestRuns(context, failedTestScreenshots);
    }

    const videoFiles = await this.getVideoFileNames(context);
    if (videoFiles.length) {
      logBuilder.appendLine("");
      logBuilder.appendLine("*** Recordings ***");
      logBuilder.appendLine(videoFiles.map((f) => `- ${f}`).join(EOL));
      logBuilder.appendLine("");

      await this.moveVideosToTestRuns(context, videoFiles);
    }

    await this.movePlaywrightReportToTestRuns(context);
  }

  /** Gets array of test video file names */
  private async getVideoFileNames(context: IRunTestContext) {
    const testResultFolder = path.join(
      context.rmProjFile.folderPath,
      StandardFolder.OutputCode,
      "test-results",
      "videos"
    );
    const files = await fs.readdir(testResultFolder);
    const videoFiles = files.filter((f) => f.toLowerCase().endsWith(".webm"));
    return videoFiles;
  }

  /** Gets array of test screenshot names */
  private async getFailedTestScreenshots(context: IRunTestContext) {
    const testResultFolder = path.join(
      context.rmProjFile.folderPath,
      StandardFolder.OutputCode,
      "test-results",
      "screenshots"
    );

    const files = await fs.readdir(testResultFolder);
    const errorScreenshotFiles = files.filter((f) => f.toLowerCase().endsWith("_error.png"));
    return errorScreenshotFiles;
  }

  /** Moves video that are generated by the run to the `test-runs/recordings` folder */
  private async moveVideosToTestRuns(context: IRunTestContext, videoFiles: string[]) {
    const testResultFolder = path.join(
      context.rmProjFile.folderPath,
      StandardFolder.OutputCode,
      "test-results",
      "videos"
    );
    let recordingsFolder = path.join(
      context.rmProjFile.folderPath,
      context.settings.testResultFolderRelPath,
      "recordings"
    );

    fs.mkdir(recordingsFolder);

    for (let file of videoFiles) {
      let filePath = path.join(testResultFolder, file);
      let moveToPath = path.join(recordingsFolder, file);
      await fs.copyFile(filePath, moveToPath);
      await fs.unlink(filePath);
    }
  }

  /** Moves error screenshot that are generated by the run to the `test-runs` folder */
  private async moveErrorScreenshotsToTestRuns(context: IRunTestContext, failedTestScreenshots: string[]) {
    const testResultFolder = path.join(
      context.rmProjFile.folderPath,
      StandardFolder.OutputCode,
      "test-results",
      "screenshots"
    );
    let errorScreenShotsFolder = path.join(
      context.rmProjFile.folderPath,
      context.settings.testResultFolderRelPath,
      "error-screenshots"
    );
    fs.mkdir(errorScreenShotsFolder);

    for (let file of failedTestScreenshots) {
      let filePath = path.join(testResultFolder, file);
      let moveToPath = path.join(errorScreenShotsFolder, file);
      await fs.copyFile(filePath, moveToPath);
      await fs.unlink(filePath);
    }
  }

  /** Moves playwright report (html) file to test-runs folder */
  private async movePlaywrightReportToTestRuns(context: IRunTestContext) {
    const playwrightReportFile = path.join(
      context.rmProjFile.folderPath,
      StandardFolder.OutputCode,
      StandardOutputFolderTypeScript.PlaywrightReport,
      "index.html"
    );
    // Copy test result file to "test-runs" folder
    const runResultFilePath = path.join(
      context.rmProjFile.folderPath,
      context.settings.testResultFolderRelPath,
      `test-result.html`
    );
    await fileSystem.copyFile(playwrightReportFile, runResultFilePath);
  }
}
