import { AutomationFramework, Indent, IRmProj, ITestCaseStep, Language, LocatorType, TestFramework } from "../../src/file-defs";
import { IPageElement } from "../../src/file-defs/pageFile";

// These interfaces in this file are only used for unit tests

/**
 * This acts as blueprint to generate an RMProject source files
 */
export interface RmpSpec {
  projectName: string;
  content: IRmProj;
  pages: IPage[];
  testcases: ITestCase[];
  testsuites: ITestSuite[];
  testroutines: ITestRoutine[];
  outputFiles: OutputCodeFile[];
  configFiles: IConfig[];
}

export interface OutputCodeFile {
  fileRelPath: string;
  fileContent: string;
}

export interface IPage {
  /** This id is auto generated by the test */
  id: string;
  name?: string;
  description?: string;
  elements: IPageElement[];
}

export interface ITestCase {
  /** This id is auto generated by the test */
  id: string;
  name?: string;
  description: string;
  steps: ITestCaseStep[];
}

export interface ITestRoutine {
  /** This id is auto generated by the test */
  id: string;
  name?: string;
  description: string;
  steps: ITestCaseStep[];
  dataSets: { id: string; name: string; description: string }[];
}

export interface ITestSuite {
  /** This id is auto generated by the test */
  id: string;
  name?: string;
  description: string;

  /** Guid refers to the test case guid */
  testcases: string[];
}
export interface IConfig {
  /** File name without extension */
  name: string;
  settings: { name: string; value: string }[];
}
